name: Build IPA

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Ruby environment (for tools like bundler, fastlane if used)
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Use your desired Ruby version

      # Install Homebrew (needed for Tuist)
      - name: Install Homebrew
        run: |
          echo | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval $(/opt/homebrew/bin/brew shellenv)' >> ~/.zprofile
          eval $(/opt/homebrew/bin/brew shellenv)

      # Install Tuist
      - name: Install Tuist
        run: |
          curl -Ls https://install.tuist.io | bash
          export PATH="$HOME/.tuist/bin:$PATH"

      # Generate Xcode project using Tuist
      - name: Generate Xcode project
        run: tuist generate

      # Build the project using Tuist
      - name: Build with Tuist
        run: tuist build --configuration Release

      # Optional: Export the .ipa if necessary (you can handle this step with Fastlane or similar)
      # If needed, you can use 'tuist archive' or set up Fastlane to handle the IPA export

      # Optional: Upload artifact (if you want to download the IPA or any build files)
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./build/